language: python
sudo: false
cache: pip
dist: trusty

matrix:
  fast_finish: true

install:
  - "python -m pip install --upgrade pip"
  - "python -m pip install -e .[tests]"
script:
  - "python -m pytest -v tests/"

jobs:
  include:
    - python: "3.7"
      dist: xenial
      sudo: required
    - python: "3.6"
    - python: "2.7"
    - python: "3.5"
    - python: "3.4"
